name: MagicArrows
version: 0.1.7
author: kaitoyuuki
main: com.github.kaitoyuuki.MagicArrows.MagicArrows
commands:

permissions:
    magicarrows.*:
        children:
            magicarrows.torch: true
            magicarrows.fire: true
            magicarrows.tnt: true
    magicarrows.torch:
        description: allows you to shoot torch arrows, which place a torch when they hit
        default: true
    magicarrows.fire:
        description: allows you to shoot real fire arrows that actually burn things
        default: op
    magicarrows.tnt:
        description: allows you to shoot explosive arrows
        default: op