name: MagicArrows
version: 0.1.11
author: kaitoyuuki
main: com.github.kaitoyuuki.MagicArrows.MagicArrows
commands:

permissions:
    magicarrows.*:
        children:
            magicarrows.torch: true
            magicarrows.fire: true
            magicarrows.tnt: true
            magicarrows.fireball: true
            magicarrows.smite: true
            magicarrows.freeze: true
    magicarrows.torch:
        description: allows you to shoot torch arrows, which place a torch when they hit
        default: true
    magicarrows.fire:
        description: allows you to shoot real fire arrows that actually burn things
        default: op
    magicarrows.tnt:
        description: allows you to shoot explosive arrows
        default: op
    magicarrows.fireball:
        description: allows you to shoot ghast fireballs
        default: op
    magicarrows.smite:
        description: allows you to summon lightning bolts to where your arrow landed
        default: op
    magicarrows.freeze:
        description: allows you to shoot freezing arrows that solidify nearby liquids
        default: op